-- BASE DE DATOS EN MYSQL

CREATE DATABASE FERRETERIA;

USE FERRETERIA;

CREATE TABLE ESTADO(
    IdEstado INT AUTO_INCREMENT,
    Estado VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY(IdEstado)
);

CREATE TABLE MUNICIPIO(
    IdMunicipio INT AUTO_INCREMENT,
    Municipio VARCHAR(50) NOT NULL,
    IdEstado INT NOT NULL,
    CONSTRAINT PK_MUNICIPIO PRIMARY KEY(IdMunicipio),
    CONSTRAINT FK_MUNICIPIOTOESTADO FOREIGN KEY(IdEstado) REFERENCES ESTADO(IdEstado)
);

CREATE TABLE CODIGOPOSTAL(
    IdCodigoPostal INT AUTO_INCREMENT,
    CodigoPostal VARCHAR(10) NOT NULL,
    IdMunicipio INT NOT NULL,
    CONSTRAINT PK_CODIGOPOSTAL PRIMARY KEY(IdCodigoPostal),
    CONSTRAINT FK_CODIGOPOSTALTOMUNICIPIO FOREIGN KEY(IdMunicipio) REFERENCES MUNICIPIO(IdMunicipio)
);

CREATE TABLE COLONIA(
    IdColonia INT AUTO_INCREMENT,
    Colonia VARCHAR(75) NOT NULL,
    IdCodigoPostal INT NOT NULL,
    CONSTRAINT PK_COLONIA PRIMARY KEY(IdColonia),
    CONSTRAINT FK_COLONIATOCODIGOPOSTAL FOREIGN KEY(IdCodigoPostal) REFERENCES CODIGOPOSTAL(IdCodigoPostal)
);

CREATE TABLE DIRECCION(
    IdDireccion INT AUTO_INCREMENT,
    IdCodigoPostal INT NOT NULL,
    IdColonia INT NOT NULL,
    Calle VARCHAR(75) NOT NULL,
    CONSTRAINT PK_DIRECCION PRIMARY KEY(IdDireccion),
    CONSTRAINT FK_DIRECCIONTOCODIGOPOSTAL FOREIGN KEY(IdCodigoPostal) REFERENCES CODIGOPOSTAL(IdCodigoPostal),
    CONSTRAINT FK_DIRECCIONTOCOLONIA FOREIGN KEY(IdColonia) REFERENCES COLONIA(IdColonia)
);

CREATE TABLE SUCURSAL(
    IdSucursal INT AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    IdDireccion INT NOT NULL,
    Telefono VARCHAR(12),
    FechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SUCURSAL PRIMARY KEY(IdSucursal),
    CONSTRAINT FK_SUCURSALTODIRECCION FOREIGN KEY(IdDireccion) REFERENCES DIRECCION(IdDireccion)
);

CREATE TABLE ROL(
  IdRol INT AUTO_INCREMENT,
  Rol VARCHAR(100),
  CONSTRAINT PK_ROL PRIMARY KEY(IdRol)
);

CREATE TABLE CATEGORIAPRODUCTO(
    IdCategoria INT AUTO_INCREMENT,
    Categoria VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY(IdCategoria)
);

CREATE TABLE RANGOCLIENTE(
    IdRangoCliente INT AUTO_INCREMENT,
    Rango VARCHAR(50) NOT NULL,
    CONSTRAINT PK_RANGOCLIENTE PRIMARY KEY(IdRangoCliente)
);

CREATE TABLE CATEGORIA_RANGO(
    Id_CategoriaRango INT AUTO_INCREMENT,
    IdRangoCliente INT NOT NULL,
    IdCategoria INT NOT NULL,
    Ganancia DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_CATEGORIA_RANGO PRIMARY KEY(Id_CategoriaRango),
    CONSTRAINT FK_CATEGORIA_RANGOTORANGOCLI FOREIGN KEY(IdRangoCliente) REFERENCES RANGOCLIENTE(IdRangoCliente),
    CONSTRAINT FK_CATEGORIA_RANGOTOCATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIAPRODUCTO(IdCategoria)
);

CREATE TABLE ESTATUS(
    IdEstatus INT AUTO_INCREMENT,
    Estatus VARCHAR(100),
    CONSTRAINT PK_ESTATUS PRIMARY KEY(IdEstatus)
);

CREATE TABLE PERSONA(
    IdPersona INT AUTO_INCREMENT,
    Nombre VARCHAR(300) NOT NULL,
    ApellidoPaterno VARCHAR(300) NOT NULL,
    ApellidoMaterno VARCHAR(300) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Edad VARCHAR(3) NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY(IdPersona)
);

CREATE TABLE EMPLEADO(
    IdEmpleado INT AUTO_INCREMENT,
    IdPersona INT NOT NULL,
    IdRol INT NOT NULL,
    IdEstatus INT NOT NULL,
    IdSucursal INT NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY(IdEmpleado),
    CONSTRAINT FK_EMPLEADOTOPERSONA FOREIGN KEY(IdPersona) REFERENCES PERSONA(IdPersona) ON DELETE CASCADE,
    CONSTRAINT FK_EMPLEADOTOESTATUS FOREIGN KEY(IdEstatus) REFERENCES ESTATUS(IdEstatus) ON DELETE CASCADE,
    CONSTRAINT FK_EMPLEADOTOROL FOREIGN KEY(IdRol) REFERENCES ROL(IdRol) ON DELETE CASCADE,
    CONSTRAINT FK_EMPLEADOTOSUCURSAL FOREIGN KEY(IdSucursal) REFERENCES SUCURSAL(IdSucursal)
);

CREATE TABLE CLIENTE(
    IdCliente INT AUTO_INCREMENT,
    IdPersona INT NOT NULL,
    IdDireccion INT NOT NULL,
    IdRangoCliente INT NOT NULL,
    Credito DECIMAL(10,2) DEFAULT 0,
    CreditoMaximo DECIMAL(10,2) DEFAULT 0,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Estatus INT DEFAULT 1,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(IdCliente),
    CONSTRAINT FK_CLIENTETOESTADO FOREIGN KEY(Estatus) REFERENCES ESTATUS(IdEstatus),
    CONSTRAINT FK_CLIENTETOPERSONA FOREIGN KEY(IdPersona) REFERENCES PERSONA(IdPersona),
    CONSTRAINT FK_CLIENTETODIRECCION FOREIGN KEY(IdDireccion) REFERENCES DIRECCION(IdDireccion),
    CONSTRAINT FK_CLIENTETORANGOCLIENTE FOREIGN KEY(IdRangoCliente) REFERENCES RANGOCLIENTE(IdRangoCliente)
);

CREATE TABLE REPARTIDOR_CLIENTE(
    IdCliente INT NOT NULL,
    IdEmpleado INT NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT PK_REPARTIDOR_CLIENTE PRIMARY KEY(IdCliente,IdEmpleado),
    CONSTRAINT FK_REPARTIDOR_CLIENTETOCLIENTE FOREIGN KEY(IdCliente) REFERENCES CLIENTE(IdCliente),
    CONSTRAINT FK_REPARTIDOR_CLIENTETOEMPLEADO FOREIGN KEY(IdEmpleado) REFERENCES EMPLEADO(IdEmpleado)
);

CREATE TABLE USUARIO(
    IdUsuario INT AUTO_INCREMENT,
    Contraseña VARCHAR(100) NOT NULL,
    IdEmpleado INT NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY(IdUsuario),
    CONSTRAINT FK_USUARIOTOEMPLEADO FOREIGN KEY(IdEmpleado) REFERENCES EMPLEADO(IdEmpleado) ON DELETE CASCADE
);

CREATE TABLE PESO(
    IdPeso INT AUTO_INCREMENT,
    PesoInicial DECIMAL(10,2) NOT NULL,
    PesoFinal DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_PESO PRIMARY KEY(IdPeso)
);

CREATE TABLE CARGO(
    IdCargo INT AUTO_INCREMENT,
    Cargo DECIMAL(10,2) NOT NULL,
    IdCategoria INT NOT NULL,
    CONSTRAINT PK_CARGO PRIMARY KEY(IdCargo),
    CONSTRAINT FK_CARGOTOCATEGORIA FOREIGN KEY(IdCategoria) REFERENCES CATEGORIAPRODUCTO(IdCategoria)
);

CREATE TABLE PRODUCTO(
    IdProducto INT AUTO_INCREMENT,
    Descripcion VARCHAR(100) NOT NULL,
    IdCategoria INT NOT NULL,
    IdPeso INT NOT NULL,
    CostoBase DECIMAL(10,2),
    CostoExtra DECIMAL(10,2),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY(IdProducto),
    CONSTRAINT FK_PRODUCTOTOPESO FOREIGN KEY(IdPeso) REFERENCES PESO(IdPeso),
    CONSTRAINT FK_PRODUCTOTOCATEGORIA FOREIGN KEY(IdCategoria) REFERENCES CATEGORIAPRODUCTO(IdCategoria)
);

CREATE TABLE INVENTARIO_SUCURSAL(
    IdInventario INT AUTO_INCREMENT,
    IdProducto INT NOT NULL,
    IdSucursal INT NOT NULL,
    Stock INT NOT NULL,
    CONSTRAINT PK_INVENTARIO_SUCURSAL PRIMARY KEY(IdInventario),
    CONSTRAINT FK_INVENTARIOTOPRODUCTO FOREIGN KEY(IdProducto) REFERENCES PRODUCTO(IdProducto),
    CONSTRAINT FK_INVENTARIOSUCURSAL FOREIGN KEY(IdSucursal) REFERENCES SUCURSAL(IdSucursal)
);

CREATE TABLE PEDIDO(
    IdPedido INT AUTO_INCREMENT,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IdEmpleado INT NOT NULL,
    IdCliente INT NOT NULL,
    RangoCliente INT NOT NULL,
    Estatus ENUM('Pendiente','Pagado', 'Enviado', 'Entregado', 'Cancelado'),
    Repartidor INT DEFAULT NULL,
    Receptor VARCHAR(100),
    MetodoPago ENUM('Contado', 'Transferencia', 'Credito'),
    CONSTRAINT PK_PEDIDO PRIMARY KEY(IdPedido),
    CONSTRAINT FK_PEDIDOTOEMPLEADO FOREIGN KEY(IdEmpleado) REFERENCES EMPLEADO(IdEmpleado),
    CONSTRAINT FK_PEDIDOTOCLIENTE FOREIGN KEY(IdCliente) REFERENCES CLIENTE(IdCliente),
    CONSTRAINT FK_PEDIDOREPARTIDORTOEMPLEADO FOREIGN KEY(Repartidor) REFERENCES EMPLEADO(IdEmpleado),
    CONSTRAINT FK_PEDIDOTORANGOCLIENTE FOREIGN KEY(RangoCliente) REFERENCES RANGOCLIENTE(IdRangoCliente)
);

CREATE TABLE PEDIDO_PRODUCTOS(
    IdPedido INT NOT NULL,
    IdProducto INT NOT NULL,
    CONSTRAINT PK_PEDIDO_PRODUCTOS PRIMARY KEY(IdPedido,IdProducto),
    CONSTRAINT FK_PEDIDO_PRODUCTOTOPEDIDO FOREIGN KEY(IdPedido) REFERENCES PEDIDO(IdPedido),
    CONSTRAINT FK_PEDIDO_PRODUCTOTOPRODUCTO FOREIGN KEY(IdProducto) REFERENCES PRODUCTO(IdProducto)
);

CREATE TABLE REGISTRO_PRODUCTO(
    IdRegistro INT AUTO_INCREMENT,
    IdProducto INT NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Accion VARCHAR(30) NOT NULL,
    Campo VARCHAR(30) NOT NULL,
    ValorAnterior VARCHAR(50) NOT NULL,
    ValorActual VARCHAR(50) NOT NULL,
    IdEmpleado INT NOT NULL,
    CONSTRAINT PK_REGISTRO_PRODUCTO PRIMARY KEY(IdRegistro),
    CONSTRAINT FK_REGISTRO_PRODTOPRODUCTO FOREIGN KEY(IdProducto) REFERENCES PRODUCTO(IdProducto),
    CONSTRAINT FK_REGISTRO_PROTOEMPLEADO FOREIGN KEY(IdEmpleado) REFERENCES EMPLEADO(IdEmpleado)
);

CREATE TABLE REGISTRO_PEDIDO(
    IdRegistro INT AUTO_INCREMENT,
    IdPedido INT NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Accion VARCHAR(30) NOT NULL,
    Campo VARCHAR(30) NOT NULL,
    ValorAnterior VARCHAR(50) NOT NULL,
    ValorActual VARCHAR(50) NOT NULL,
    IdEmpleado INT NOT NULL,
    CONSTRAINT PK_REGISTRO_PEDIDO PRIMARY KEY(IdRegistro),
    CONSTRAINT FK_REGISTRO_PEDIDOTOPEDIDO FOREIGN KEY(IdPedido) REFERENCES PEDIDO(IdPedido),
    CONSTRAINT FK_REGISTRO_PEDIDOTOEMPLEADO FOREIGN KEY(IdEmpleado) REFERENCES EMPLEADO(IdEmpleado)
);

CREATE TABLE REGISTRO_CLIENTE(
    IdRegistro INT AUTO_INCREMENT,
    IdCliente INT NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Accion VARCHAR(30) NOT NULL,
    Campo VARCHAR(30) NOT NULL,
    ValorAnterior VARCHAR(50) NOT NULL,
    ValorActual VARCHAR(50) NOT NULL,
    IdEmpleado INT NOT NULL,
    CONSTRAINT PK_REGISTRO_CLIENTE PRIMARY KEY(IdRegistro),
    CONSTRAINT FK_REGISTRO_CLIENTETOPEDIDO FOREIGN KEY(IdCliente) REFERENCES CLIENTE(IdCliente),
    CONSTRAINT FK_REGISTRO_CLIENTETOEMPLEADO FOREIGN KEY(IdEmpleado) REFERENCES EMPLEADO(IdEmpleado)
);

CREATE TABLE BITACORA(
    IdBitacora INT AUTO_INCREMENT,
    Usuario INT NOT NULL,
    Accion ENUM('INSERT', 'UPDATE', 'DELETE'),
    TablaAfectada VARCHAR(50),
    IdRegistro INT NOT NULL, -- REGISTRO AFECTADO
    Campo VARCHAR(50),
    ValorAnterior VARCHAR(300),
    ValorNuevo VARCHAR(300),
    Fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_BITACORA PRIMARY KEY(IdBitacora),
    CONSTRAINT FK_BITACORATOUSUARIO FOREIGN KEY(Usuario) REFERENCES USUARIO(IdUsuario)
);

ALTER TABLE USUARIO AUTO_INCREMENT = 1001;
SET time_zone = 'America/Mexico_City';

-- DIRECCIONES
DROP FUNCTION  IF EXISTS ObtenerDireccionBYCP;
CREATE FUNCTION ObtenerDireccionBYCP(ID INT)
RETURNS VARCHAR(100)
    DETERMINISTIC
    BEGIN
        DECLARE DIRECCION VARCHAR(100);
        SET DIRECCION = (SELECT CONCAT(E.Estado, ' ', M.Municipio, ' ', C2.Colonia, ' ', C.CodigoPostal) AS DIRECCION FROM ESTADO AS E INNER JOIN MUNICIPIO AS M ON E.IdEstado = M.IdEstado INNER JOIN CODIGOPOSTAL AS C ON M.IdMunicipio = C.IdMunicipio INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = ID LIMIT 1);
        RETURN DIRECCION;
    end;

DROP FUNCTION IF EXISTS FN_OBTENERDIRECCION;
CREATE FUNCTION FN_OBTENERDIRECCION(IDDIR INT)
    RETURNS VARCHAR(100)
    DETERMINISTIC
    BEGIN
        DECLARE DIRECCION VARCHAR(100);
        DECLARE IDCOL INT;
        SET IDCOL = (SELECT IdColonia FROM DIRECCION WHERE IdDireccion = IDDIR LIMIT 1);
        SET DIRECCION = (SELECT CONCAT(D.Calle, ', ', C2.Colonia, ', ', C.CodigoPostal, ', ', M.Municipio, ', ', E.Estado, ', ', 'México') FROM DIRECCION AS D INNER JOIN CODIGOPOSTAL C on D.IdCodigoPostal = C.IdCodigoPostal INNER JOIN MUNICIPIO M on C.IdMunicipio = M.IdMunicipio INNER JOIN ESTADO E on M.IdEstado = E.IdEstado INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE D.IdDireccion = IDDIR AND C2.IdColonia = IDCOL LIMIT 1);
        RETURN DIRECCION;
    end;

DROP PROCEDURE IF EXISTS SP_OBTENERCOLONIAS;
CREATE PROCEDURE SP_OBTENERCOLONIAS(IN COD VARCHAR(10))
    BEGIN
        SELECT M.Municipio FROM CODIGOPOSTAL AS C INNER JOIN MUNICIPIO M on C.IdMunicipio = M.IdMunicipio WHERE C.CodigoPostal = COD LIMIT 1;
        SELECT C2.Colonia, C2.IdColonia AS VALUE FROM CODIGOPOSTAL AS C INNER JOIN COLONIA AS C2 ON C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = COD;
        SELECT E.Estado FROM CODIGOPOSTAL AS C INNER JOIN MUNICIPIO AS M ON C.IdMunicipio = M.IdMunicipio INNER JOIN ESTADO AS E ON M.IdEstado = E.IdEstado WHERE C.CodigoPostal = COD LIMIT 1;
    end;

DROP PROCEDURE IF EXISTS SP_REGISTRARDIRECCION;
CREATE PROCEDURE SP_REGISTRARDIRECCION(IN COD VARCHAR(10), IN COL INT, IN CALLEIN VARCHAR(75), IN USERIN INT, OUT IDDIRVAR INT)
    BEGIN
        DECLARE IDCODVAR INT;
        SET IDCODVAR = (SELECT IdCodigoPostal FROM CODIGOPOSTAL AS C WHERE CodigoPostal = COD LIMIT 1);
        INSERT INTO DIRECCION (IdCodigoPostal, IdColonia, Calle) VALUES (IDCODVAR, COL, CALLEIN);
        SET IDDIRVAR = (SELECT LAST_INSERT_ID());
        INSERT INTO BITACORA (Usuario, Accion, TablaAfectada, IdRegistro, Campo, ValorAnterior, ValorNuevo) VALUES (USERIN, 'INSERT', 'DIRECCION', IDDIRVAR, 'Todos','',(SELECT CONCAT(D.Calle, ', ', C.CodigoPostal, ', ', M.Municipio, ', ', E.Estado) FROM DIRECCION AS D INNER JOIN CODIGOPOSTAL AS C ON D.IdCodigoPostal = C.IdCodigoPostal INNER JOIN MUNICIPIO M on C.IdMunicipio = M.IdMunicipio INNER JOIN ESTADO E on M.IdEstado = E.IdEstado WHERE D.IdDireccion = IDDIRVAR LIMIT 1));
    end;

-- SUCURSALES

DROP PROCEDURE IF EXISTS SP_REGISTRARSUCURSAL;
CREATE PROCEDURE SP_REGISTRARSUCURSAL(IN COD VARCHAR(10), IN COL INT, IN CALLEIN VARCHAR(75), IN NOMBREIN VARCHAR(50), IN TELEFONOIN VARCHAR(12), IN USERIN INT)
    BEGIN
        DECLARE LASTIDSUC INT;
        DECLARE IDDIR INT;
        CALL SP_REGISTRARDIRECCION(COD, COL, CALLEIN, USERIN, IDDIR);
        INSERT INTO SUCURSAL (Nombre, IdDireccion, Telefono) VALUE (NOMBREIN, IDDIR, TELEFONOIN);
        SET LASTIDSUC = (SELECT LAST_INSERT_ID());
        INSERT INTO BITACORA (Usuario, Accion, TablaAfectada, IdRegistro, Campo, ValorAnterior, ValorNuevo) VALUES (USERIN, 'INSERT', 'SUCURSAL', LASTIDSUC, 'Todos', '', (SELECT Nombre FROM SUCURSAL WHERE IdSucursal = LASTIDSUC));
        SELECT 1 AS RES;
    end;

DROP PROCEDURE IF EXISTS SP_GETSUCURSALES;
CREATE PROCEDURE SP_GETSUCURSALES()
    BEGIN
        SELECT S.IdSucursal, S.Nombre, (SELECT FN_OBTENERDIRECCION(S.IdDireccion)) AS Direccion, S.Telefono, S.FechaRegistro  FROM SUCURSAL AS S;
    end;

-- LOGIN
DROP PROCEDURE IF EXISTS LOGIN;
CREATE PROCEDURE LOGIN(IN ID INT, IN PASSWORD VARCHAR(50))
BEGIN
    DECLARE USERREGISTER INT;
    DECLARE PASST INT;
    DECLARE USERSTATUS INT;


    SET USERREGISTER = (SELECT IdUsuario FROM USUARIO WHERE IdUsuario = ID);
    IF USERREGISTER IS NULL THEN
        SELECT 0 AS RES; -- EL USUARIO NO EXISTE
    ELSE
        SET PASST = (SELECT IdUsuario FROM USUARIO WHERE IdUsuario = ID AND Contraseña = PASSWORD);
        IF PASST IS NULL THEN
            SELECT 1 AS RES; -- CONTRASEÑA INCORRECTA
        ELSE
            SET USERSTATUS = (SELECT IdEstatus FROM EMPLEADO AS E INNER JOIN USUARIO AS U ON E.IdEmpleado = U.IdEmpleado WHERE U.IdUsuario = ID );
            IF USERSTATUS != 1 THEN
                SELECT 2 AS RES; -- EL ESTATUS NO ESTA ACTIVO
            ELSE
                SELECT U.IdUsuario, E.IdRol, E.IdEstatus, P.Nombre, P.ApellidoPaterno AS Apellido, E.IdSucursal AS Sucursal FROM USUARIO AS U INNER JOIN EMPLEADO AS E ON U.IdEmpleado = E.IdEmpleado INNER JOIN PERSONA AS P ON E.IdPersona = P.IdPersona WHERE IdUsuario = ID AND Contraseña = PASSWORD;
            end if;
        end if;
    end if;
END;

DROP PROCEDURE IF EXISTS LOGIN_ESTATUS; --   PARA QUE FUNCIONE CON EL HASH DE CONTRASEÑAS
CREATE PROCEDURE LOGIN_ESTATUS(IN ID INT, IN OPT INT)
BEGIN
    DECLARE USERREGISTER INT;
    DECLARE USERSTATUS INT;

    IF OPT = 1 THEN
        SELECT Contraseña FROM USUARIO WHERE IdUsuario = ID;
    ELSE
        SET USERREGISTER = (SELECT IdUsuario FROM USUARIO WHERE IdUsuario = ID);
        IF USERREGISTER IS NULL THEN
            SELECT 0 AS RES; -- EL USUARIO NO EXISTE
        ELSE
            SET USERSTATUS = (SELECT IdEstatus FROM EMPLEADO AS E INNER JOIN USUARIO AS U ON E.IdEmpleado = U.IdEmpleado WHERE U.IdUsuario = ID );
            IF USERSTATUS != 1 THEN
                SELECT 1 AS RES; -- EL ESTATUS NO ESTA ACTIVO
            ELSE
                SELECT 2 AS RES; -- EL USUARIO EXISTE Y ESTA ACTIVO
            end if;
        end if;
    end if;
END;

DROP PROCEDURE IF EXISTS SP_GETUSERINFO;
CREATE PROCEDURE SP_GETUSERINFO(IN ID INT)
    BEGIN
        SELECT U.IdUsuario, E.IdRol, E.IdEstatus, P.Nombre, P.ApellidoPaterno AS Apellido, E.IdSucursal AS Sucursal FROM USUARIO AS U INNER JOIN EMPLEADO AS E ON U.IdEmpleado = E.IdEmpleado INNER JOIN PERSONA AS P ON E.IdPersona = P.IdPersona WHERE IdUsuario = ID;
    end;

-- Administrador/Empleados

DROP PROCEDURE IF EXISTS SP_REGISTRARPERSONA;
CREATE PROCEDURE SP_REGISTRARPERSONA(IN NOMBREIN VARCHAR(300), IN APELLIDOPAT VARCHAR(300), IN APELLIDOMAT VARCHAR(300), IN TELEFONOIN VARCHAR(300), IN EDADIN VARCHAR(3), IN USERIN INT, OUT LASTIDPER INT)
    BEGIN
        INSERT INTO PERSONA (Nombre, ApellidoPaterno, ApellidoMaterno, Telefono, Edad) VALUES (NOMBREIN, APELLIDOPAT, APELLIDOMAT, TELEFONOIN, EDADIN);
        SET LASTIDPER = (SELECT LAST_INSERT_ID());
        INSERT INTO BITACORA (Usuario, Accion, TablaAfectada, IdRegistro, Campo, ValorAnterior, ValorNuevo) VALUES (USERIN, 'INSERT', 'PERSONA', LASTIDPER, 'Todos', '', (SELECT CONCAT(Nombre, ' ', ApellidoPaterno) FROM PERSONA WHERE IdPersona = LASTIDPER));
    end;

DROP PROCEDURE IF EXISTS SP_REGISTRAREMPLEADO;
CREATE PROCEDURE SP_REGISTRAREMPLEADO(IN CONTRASEÑAIN VARCHAR(100), IN NOMBREIN VARCHAR(300), IN APELLIDOPAT VARCHAR(300), IN APELLIDOMAT VARCHAR(300), IN TELEFONOIN VARCHAR(300), IN EDADIN VARCHAR(3), IN IDROLIN INT, IN IDEST INT, IN IDSUC INT, IN USERIN INT)
    BEGIN
        DECLARE  IdEMPVAR INT;
        DECLARE IDPERVAR INT;

        CALL SP_REGISTRARPERSONA(NOMBREIN, APELLIDOPAT, APELLIDOMAT, TELEFONOIN, EDADIN, USERIN, IDPERVAR);
        INSERT INTO EMPLEADO (IdPersona, IdRol, IdEstatus, IdSucursal) VALUES (IDPERVAR, IDROLIN, IDEST, IDSUC);
        SET IdEMPVAR = (SELECT LAST_INSERT_ID());
        INSERT INTO BITACORA (Usuario, Accion, TablaAfectada, IdRegistro, Campo, ValorAnterior, ValorNuevo) VALUES (USERIN, 'INSERT', 'EMPLEADO', IdEMPVAR, 'Todos', '', (SELECT CONCAT(P.Nombre, ' ', P.ApellidoPaterno) FROM EMPLEADO AS E INNER JOIN PERSONA P on E.IdPersona = P.IdPersona WHERE E.IdEmpleado = IdEMPVAR));
        INSERT INTO USUARIO (Contraseña, IdEmpleado) VALUES (CONTRASEÑAIN, IdEMPVAR);
        SET IdEMPVAR = (SELECT LAST_INSERT_ID());
        INSERT INTO BITACORA (Usuario, Accion, TablaAfectada, IdRegistro, Campo, ValorAnterior, ValorNuevo) VALUES (USERIN, 'INSERT', 'USUARIO', IdEMPVAR, 'Todos', '', (SELECT CONCAT(P.Nombre, ' ', P.ApellidoPaterno) FROM EMPLEADO AS E INNER JOIN PERSONA P on E.IdPersona = P.IdPersona INNER JOIN USUARIO U on E.IdEmpleado = U.IdEmpleado WHERE U.IdUsuario = IdEMPVAR));
    end;

DROP PROCEDURE IF EXISTS SP_GETEMPLEADOS;
CREATE PROCEDURE SP_GETEMPLEADOS(IN IDEMP INT, IN SUCURSALIN INT)
    BEGIN
        SELECT U.IdUsuario AS ID, E.IdEmpleado AS IdEmp, CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) AS Nombre, P.Telefono, P.Edad, R.Rol, S.Nombre AS Sucursal, E2.Estatus FROM EMPLEADO AS E INNER JOIN PERSONA P on E.IdPersona = P.IdPersona INNER JOIN ROL R on E.IdRol = R.IdRol INNER JOIN SUCURSAL S on E.IdSucursal = S.IdSucursal INNER JOIN ESTATUS E2 on E.IdEstatus = E2.IdEstatus INNER JOIN USUARIO U on E.IdEmpleado = U.IdEmpleado WHERE E2.IdEstatus != 4 AND U.IdUsuario != IDEMP AND E.IdSucursal = SUCURSALIN ORDER BY U.IdUsuario;
    end;

DROP PROCEDURE IF EXISTS SP_DELETEEMPLEADO;
CREATE PROCEDURE SP_DELETEEMPLEADO(IN ID INT, IN USERID INT)
    BEGIN
        DECLARE NOMBREVAR VARCHAR(100);
        SET NOMBREVAR = (SELECT CONCAT(P.Nombre, ' ', P.ApellidoPaterno) FROM USUARIO AS U INNER JOIN  EMPLEADO E2 on U.IdEmpleado = E2.IdEmpleado INNER JOIN PERSONA P on E2.IdPersona = P.IdPersona WHERE E2.IdEmpleado = ID);
        UPDATE EMPLEADO SET IdEstatus = 4 WHERE IdEmpleado = ID;
        INSERT INTO BITACORA (Usuario, Accion, TablaAfectada, IdRegistro, Campo, ValorAnterior, ValorNuevo) VALUES (USERID, 'DELETE', 'EMPLEADO', ID, 'Todos', NOMBREVAR, '');
    end;

DROP PROCEDURE IF EXISTS SP_GETNOMBRESUCURSALES;
CREATE  PROCEDURE SP_GETSUCURSALESNOMBRES()
    BEGIN
        SELECT Nombre AS Nombre, IdSucursal AS Id FROM SUCURSAL;
    end;

DROP PROCEDURE IF EXISTS SP_GETEMPLEADO;
CREATE PROCEDURE SP_GETEMPLEADO(IN IDIN INT)
    BEGIN
        SELECT P.Nombre, P.ApellidoPaterno, P.ApellidoMaterno, P.Edad, P.Telefono, E.IdSucursal AS Sucursal, S.Nombre AS NombreSucursal, E.IdRol AS 'Rol', R.Rol AS NombreRol, E.IdEstatus AS 'Estatus' FROM PERSONA AS P INNER JOIN EMPLEADO AS E ON P.IdPersona = E.IdPersona INNER JOIN SUCURSAL S on E.IdSucursal = S.IdSucursal INNER JOIN ROL R on E.IdRol = R.IdRol WHERE E.IdEmpleado = IDIN;
    end;

DROP PROCEDURE IF EXISTS SP_REGISTRARACTUZALICACION;
CREATE PROCEDURE SP_REGISTRARACTUZALICACION(IN USERIN INT, IN TABLAAFECT VARCHAR(50), IN IDREGISTROVAR INT, IN CAMPOIN VARCHAR(100), IN VALORANTERIORIN VARCHAR(100), VALORNUEVOIN VARCHAR(100))
    BEGIN
        INSERT INTO BITACORA (Usuario, Accion, TablaAfectada, IdRegistro, Campo, ValorAnterior, ValorNuevo) VALUES (USERIN, 'UPDATE', TABLAAFECT, IDREGISTROVAR, CAMPOIN, VALORANTERIORIN, VALORNUEVOIN);
    end;

DROP PROCEDURE IF EXISTS SP_UPDATEEMPLEADO;
CREATE PROCEDURE SP_UPDATEEMPLEADO(IN EMPLEADOIN INT, IN NOMBREIN VARCHAR(50), IN APELLIDOPAT VARCHAR(50), IN APELLIDOMAT VARCHAR(50), IN EDADIN VARCHAR(3), IN TELEFONOIN VARCHAR(10), IN SUCURSALIN INT, IN ROLIN INT, IN ESTATUSIN INT)
    BEGIN
        DECLARE IDPERSONAVAR INT;
        SET IDPERSONAVAR = (SELECT P.IdPersona FROM PERSONA AS P INNER JOIN EMPLEADO E on P.IdPersona = E.IdPersona WHERE E.IdEmpleado = EMPLEADOIN);

        IF IDPERSONAVAR IS NULL THEN
            SELECT 2 AS RES;
        ELSE
            SELECT 1 AS RES;
        end if;

        UPDATE PERSONA SET Nombre = NOMBREIN, ApellidoPaterno = APELLIDOPAT, ApellidoMaterno = APELLIDOMAT, Edad = EDADIN, Telefono = TELEFONOIN WHERE IdPersona = IDPERSONAVAR;
        UPDATE EMPLEADO SET IdSucursal = SUCURSALIN, IdEstatus = ESTATUSIN, IdRol = ROLIN WHERE IdEmpleado = EMPLEADOIN;
    end;

DROP PROCEDURE IF EXISTS SP_FINDEMPLEADO;
CREATE PROCEDURE SP_FINDEMPLEADO(IN NOMBREIN VARCHAR(100))
    BEGIN
        SELECT U.IdUsuario AS ID, E.IdEmpleado AS IdEmp, CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) AS Nombre, P.Telefono, P.Edad, R.Rol, S.Nombre AS Sucursal, E2.Estatus FROM EMPLEADO AS E INNER JOIN PERSONA P on E.IdPersona = P.IdPersona INNER JOIN ROL R on E.IdRol = R.IdRol INNER JOIN SUCURSAL S on E.IdSucursal = S.IdSucursal INNER JOIN ESTATUS E2 on E.IdEstatus = E2.IdEstatus INNER JOIN USUARIO U on E.IdEmpleado = U.IdEmpleado WHERE E2.IdEstatus != 4 AND CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) LIKE CONCAT(NOMBREIN, '%') ORDER BY U.IdUsuario;
    end;

-- CLIENTES

DROP PROCEDURE IF EXISTS SP_ADDCLIENTE;
CREATE PROCEDURE SP_ADDCLIENTE(IN COD VARCHAR(10), IN COL INT, IN CALLEIN VARCHAR(75), IN NOMBREIN VARCHAR(300), IN APELLIDOPAT VARCHAR(300), IN APELLIDOMAT VARCHAR(300), IN TELEFONOIN VARCHAR(300), IN EDADIN VARCHAR(3), IN RANGOIN INT, IN CREDITOMAX INT, IN USERIN INT)
    BEGIN
        DECLARE IDDIR INT;
        DECLARE IDPERVAR INT;
        DECLARE CLIENTEVAR INT;
        CALL SP_REGISTRARDIRECCION(COD, COL, CALLEIN, USERIN, IDDIR);
        CALL SP_REGISTRARPERSONA(NOMBREIN, APELLIDOPAT, APELLIDOMAT, TELEFONOIN, EDADIN, USERIN, IDPERVAR);
        INSERT INTO CLIENTE (IdPersona, IdDireccion, IdRangoCliente, CreditoMaximo) VALUES (IDPERVAR, IDDIR, RANGOIN, CREDITOMAX);
        SET CLIENTEVAR = (SELECT LAST_INSERT_ID());
        INSERT INTO BITACORA (Usuario, Accion, TablaAfectada, IdRegistro, Campo, ValorAnterior, ValorNuevo) VALUES (USERIN, 'INSERT', 'CLIENTE', CLIENTEVAR, 'Todos', '', (SELECT Nombre FROM PERSONA WHERE IdPersona = IDPERVAR));
    end;

DROP PROCEDURE IF EXISTS SP_GETCLIENTES;
CREATE PROCEDURE SP_GETCLIENTES()
    BEGIN
        SELECT C.IdCliente AS Id, CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) AS Nombre, P.Telefono, (SELECT FN_OBTENERDIRECCION(C.IdDireccion)) AS Direccion, P.Edad, R.Rango, FORMAT(C.Credito,2) AS Credito, FORMAT(C.CreditoMaximo,2) AS CreditoMaximo, C.Fecha FROM CLIENTE AS C INNER JOIN PERSONA AS P ON C.IdPersona = P.IdPersona INNER JOIN RANGOCLIENTE AS R ON C.IdRangoCliente = R.IdRangoCliente WHERE C.Estatus = 1;
    end;

DROP PROCEDURE IF EXISTS SP_FINDCLIENTE;
CREATE PROCEDURE SP_FINDCLIENTE(IN NOMBREIN VARCHAR(70))
    BEGIN
        SELECT C.IdCliente AS Id, CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) AS Nombre, P.Telefono, (SELECT FN_OBTENERDIRECCION(C.IdDireccion)) AS Direccion, P.Edad, R.Rango, FORMAT(C.Credito,2) AS Credito, FORMAT(C.CreditoMaximo,2) AS CreditoMaximo, C.Fecha FROM CLIENTE AS C INNER JOIN PERSONA AS P ON C.IdPersona = P.IdPersona INNER JOIN RANGOCLIENTE AS R ON C.IdRangoCliente = R.IdRangoCliente WHERE CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) LIKE CONCAT(NOMBREIN, '%') AND C.Estatus = 1;
    end;

DROP PROCEDURE IF EXISTS SP_DELETECLIENTE;
CREATE PROCEDURE SP_DELETECLIENTE(IN ID INT, IN USERID INT)
    BEGIN
        DECLARE NOMBREVAR VARCHAR(100);
        SET NOMBREVAR = (SELECT CONCAT(P.Nombre, ' ', P.ApellidoPaterno) FROM CLIENTE AS C INNER JOIN PERSONA P on C.IdPersona = P.IdPersona WHERE C.IdCliente = ID);
        UPDATE CLIENTE SET Estatus = 4 WHERE IdCliente = ID;
        INSERT INTO BITACORA (Usuario, Accion, TablaAfectada, IdRegistro, Campo, ValorAnterior, ValorNuevo) VALUES (USERID, 'DELETE', 'CLIENTE', ID, 'Todos', NOMBREVAR, '');
    end;

DROP PROCEDURE IF EXISTS SP_GETCLIENTEBYID;
CREATE PROCEDURE SP_GETCLIENTEBYID(IN IDCLIENTE INT)
    BEGIN
        SELECT P.Nombre, P.ApellidoPaterno, P.ApellidoMaterno, P.Telefono, C2.CodigoPostal AS Codigo, D.IdColonia AS Colonia, C3.Colonia AS NombreColonia, D.Calle, P.Edad, R.IdRangoCliente AS Rango, R.Rango AS NombreRango, C.CreditoMaximo FROM CLIENTE AS C INNER JOIN PERSONA AS P ON C.IdPersona = P.IdPersona INNER JOIN RANGOCLIENTE AS R ON C.IdRangoCliente = R.IdRangoCliente INNER JOIN DIRECCION D on C.IdDireccion = D.IdDireccion INNER JOIN CODIGOPOSTAL C2 on D.IdCodigoPostal = C2.IdCodigoPostal INNER JOIN COLONIA C3 on C2.IdCodigoPostal = C3.IdCodigoPostal WHERE C.Estatus = 1 AND C.IdCliente = IDCLIENTE;
    end;

DROP PROCEDURE IF EXISTS SP_UPDATECLIENTE;
CREATE PROCEDURE SP_UPDATECLIENTE(IN CLIENTEIN INT, IN NOMBREIN VARCHAR(50), IN APELLIDOPAT VARCHAR(50), IN APELLIDOMAT VARCHAR(50), IN EDADIN VARCHAR(3), IN TELEFONOIN VARCHAR(10), IN CODIGOIN INT, IN CALLEIN VARCHAR(100), IN COLONIAIN INT, IN RANGOIN INT, CREDITOMAXIMOIN DECIMAL(10,2))
    BEGIN
        DECLARE IDPERSONAVAR INT;
        DECLARE IDDIRECCIONVAR INT;
        SET IDDIRECCIONVAR = (SELECT D.IdDireccion FROM DIRECCION AS D INNER JOIN CLIENTE C2 on D.IdDireccion = C2.IdDireccion WHERE C2.IdCliente = CLIENTEIN LIMIT 1);
        SET IDPERSONAVAR = (SELECT P.IdPersona FROM PERSONA AS P INNER JOIN CLIENTE C on P.IdPersona = C.IdPersona WHERE C.IdCliente = CLIENTEIN LIMIT 1);

        IF IDPERSONAVAR IS NULL THEN
            SELECT 2 AS RES;
        ELSE
            SELECT 1 AS RES;
        end if;

        UPDATE PERSONA SET Nombre = NOMBREIN, ApellidoPaterno = APELLIDOPAT, ApellidoMaterno = APELLIDOMAT, Edad = EDADIN, Telefono = TELEFONOIN WHERE IdPersona = IDPERSONAVAR;
        UPDATE DIRECCION SET IdCodigoPostal = (SELECT C.IdCodigoPostal FROM CODIGOPOSTAL AS C WHERE C.CodigoPostal = CODIGOIN LIMIT 1), IdColonia = COLONIAIN, Calle = CALLEIN WHERE IdDireccion = IDDIRECCIONVAR;
        UPDATE CLIENTE SET IdRangoCliente = RANGOIN, CreditoMaximo = CREDITOMAXIMOIN WHERE IdCliente = CLIENTEIN;
    end;
--

CALL SP_ADDCLIENTE('38800',72856, 'Prueba 123', 'Julian', 'Mendoza', 'Guzman', '4454554675', '23', 1, 0, 1001);
CALL SP_ADDCLIENTE('38800',72856, 'Prueba 123', 'Pedro', 'Alvarez', 'Guzman', '4454554675', '23', 1, 0, 1001);

-- REGISTROS

DROP FUNCTION IF EXISTS FN_GETNAMEBYUSERID; -- FUNCION PARA OBTENER EL NOMBRE MEDIANTE EL USERID
CREATE FUNCTION FN_GETNAMEBYUSERID(USERID INT)
    RETURNS VARCHAR(100)
    DETERMINISTIC
    BEGIN
       DECLARE NOMBREUSER VARCHAR(100);
       SET NOMBREUSER = (SELECT CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) FROM USUARIO AS U INNER JOIN EMPLEADO E on U.IdEmpleado = E.IdEmpleado INNER JOIN PERSONA P on E.IdPersona = P.IdPersona WHERE U.IdUsuario = USERID);
       RETURN NOMBREUSER;
    end;

DROP PROCEDURE IF EXISTS SP_GETREGISTROS;
CREATE PROCEDURE SP_GETREGISTROS(IN TABLAIN VARCHAR(50))
    BEGIN
        IF TABLAIN = 'CLIENTE' THEN
            SELECT B.IdBitacora, B.Accion ,(SELECT FN_GETNAMEBYUSERID(B.Usuario)) AS Usuario, CONCAT(P.Nombre, ' ', P.ApellidoPaterno, ' ', P.ApellidoMaterno) AS Nombre, B.Campo, B.ValorAnterior, B.ValorNuevo, B.Fecha  FROM BITACORA AS B INNER JOIN CLIENTE C on B.IdRegistro = C.IdCliente INNER JOIN PERSONA P on C.IdPersona = P.IdPersona WHERE B.TablaAfectada = 'CLIENTE';
        end if;
    end;
select * from BITACORA WHERE TablaAfectada = 'SUCURSAL';

CALL LOGIN(1001, '123456');

SELECT * FROM USUARIO;


SELECT ObtenerDireccionBYCP(38940);

SELECT CONCAT(E.Estado, ' ', M.Municipio, ' ', C2.Colonia, ' ', C.CodigoPostal) AS DIRECCION FROM ESTADO AS E INNER JOIN MUNICIPIO AS M ON E.IdEstado = M.IdEstado INNER JOIN CODIGOPOSTAL AS C ON M.IdMunicipio = C.IdMunicipio INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = 29000;

SELECT CONCAT(E.IdEstado, ' ', M.IdMunicipio, ' ', C2.Colonia, ' ', C.CodigoPostal) AS DIRECCION FROM ESTADO AS E INNER JOIN MUNICIPIO AS M ON E.IdEstado = M.IdEstado INNER JOIN CODIGOPOSTAL AS C ON M.IdMunicipio = C.IdMunicipio INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = 29000;

CALL SP_OBTENERCOLONIAS('38800');

select * from ESTATUS;

-- DATOS INICIALES

INSERT INTO DIRECCION (IdCodigoPostal, IdColonia, Calle) SELECT IdCodigoPostal, 72856, 'Victoria 54' FROM CODIGOPOSTAL WHERE CodigoPostal = '38800' LIMIT 1;
INSERT INTO SUCURSAL (Nombre, IdDireccion, Telefono) VALUE ('Sucursal Moroleón', (SELECT LAST_INSERT_ID()), '4456439861');
INSERT INTO DIRECCION (IdCodigoPostal, IdColonia, Calle) SELECT IdCodigoPostal, 119795, 'Allende 32' FROM CODIGOPOSTAL WHERE CodigoPostal = '58000' LIMIT 1;
INSERT INTO SUCURSAL (Nombre, IdDireccion, Telefono) VALUE ('Sucursal Morelia', (SELECT LAST_INSERT_ID()), '4437812064');

INSERT INTO ROL (Rol) VALUE ('Vendedor');
INSERT INTO ROL (Rol) VALUE ('Cajero');
INSERT INTO ROL (Rol) VALUE ('Administrador');

INSERT INTO ESTATUS (ESTATUS) VALUES ('Activo');
INSERT INTO ESTATUS (ESTATUS) VALUES ('Despedido');
INSERT INTO ESTATUS (ESTATUS) VALUES ('Suspendido');
INSERT INTO ESTATUS (ESTATUS) VALUES ('Eliminado');

INSERT INTO PERSONA (Nombre, ApellidoPaterno, ApellidoMaterno, Telefono, Edad) VALUES ('Pedro', 'Villa', 'Almanza', '4457963475', '45');
INSERT INTO EMPLEADO (IdPersona, IdRol, IdEstatus, IdSucursal) VALUES ((SELECT LAST_INSERT_ID()), 3, 1, 1);
INSERT INTO USUARIO (Contraseña, IdEmpleado) VALUES ('$2b$10$VuHF8B70UNBN.MmD6vS20eigaxYkUjkCi.mcxtRVJqQwpnDkua2jq', 1);

INSERT INTO RANGOCLIENTE (Rango) VALUES ('Público 1');
INSERT INTO RANGOCLIENTE (Rango) VALUES ('Herrero 2');
INSERT INTO RANGOCLIENTE (Rango) VALUES ('Herrero 3');
INSERT INTO RANGOCLIENTE (Rango) VALUES ('Herrero 4');
INSERT INTO RANGOCLIENTE (Rango) VALUES ('Mayoreo 1');
INSERT INTO RANGOCLIENTE (Rango) VALUES ('Mayoreo 2');

--


CALL SP_REGISTRAREMPLEADO('123456','Francisco', 'Leal', 'Medina', '4459721648', '32', 3, 1, 2,1001);



CALL SP_REGISTRARSUCURSAL('38800', 72856, 'Ejemplo 21', 'Sucursal Ejemplo', '4451239843',1001);


SELECT * FROM CLIENTE;
SELECT * FROM BITACORA;

SELECT * FROM USUARIO;

SELECT * FROM EMPLEADO;

SELECT * FROM ROL;

UPDATE EMPLEADO SET IdEstatus = 1 WHERE IdEmpleado = 1;

UPDATE EMPLEADO SET IdRol = 3 WHERE IdEmpleado = 2;

SELECT * FROM USUARIO;

UPDATE USUARIO SET Contraseña = '$2b$10$VuHF8B70UNBN.MmD6vS20eigaxYkUjkCi.mcxtRVJqQwpnDkua2jq' WHERE IdUsuario = 1001;

SELECT * FROM PERSONA;
UPDATE EMPLEADO SET IdSucursal = 2 WHERE IdEmpleado = 1;
select * from CODIGOPOSTAL;

CALL SP_OBTENERCOLONIAS('20263');


