CREATE DATABASE TEST;
USE TEST;


CREATE TABLE ESTADO(
    IdEstado INT AUTO_INCREMENT,
    Estado VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY(IdEstado)
);

CREATE TABLE MUNICIPIO(
    IdMunicipio INT AUTO_INCREMENT,
    Municipio VARCHAR(50) NOT NULL,
    IdEstado INT NOT NULL,
    CONSTRAINT PK_MUNICIPIO PRIMARY KEY(IdMunicipio),
    CONSTRAINT FK_MUNICIPIOTOESTADO FOREIGN KEY(IdEstado) REFERENCES ESTADO(IdEstado)
);

CREATE TABLE CODIGOPOSTAL(
    IdCodigoPostal INT AUTO_INCREMENT,
    CodigoPostal VARCHAR(10) NOT NULL,
    IdMunicipio INT NOT NULL,
    Latitud DECIMAL(10,6),
    Longitud DECIMAL(10,6),
    CONSTRAINT PK_CODIGOPOSTAL PRIMARY KEY(IdCodigoPostal),
    CONSTRAINT FK_CODIGOPOSTALTOMUNICIPIO FOREIGN KEY(IdMunicipio) REFERENCES MUNICIPIO(IdMunicipio)
);

CREATE TABLE COLONIA(
    IdColonia INT AUTO_INCREMENT,
    Colonia VARCHAR(75) NOT NULL,
    IdCodigoPostal INT NOT NULL,
    CONSTRAINT PK_COLONIA PRIMARY KEY(IdColonia),
    CONSTRAINT FK_COLONIATOCODIGOPOSTAL FOREIGN KEY(IdCodigoPostal) REFERENCES CODIGOPOSTAL(IdCodigoPostal)
);

CREATE TABLE DIRECCION(
    IdDireccion INT AUTO_INCREMENT,
    IdCodigoPostal INT NOT NULL,
    IdColonia INT NOT NULL,
    Calle VARCHAR(75) NOT NULL,
    CONSTRAINT PK_DIRECCION PRIMARY KEY(IdDireccion),
    CONSTRAINT FK_DIRECCIONTOCODIGOPOSTAL FOREIGN KEY(IdCodigoPostal) REFERENCES CODIGOPOSTAL(IdCodigoPostal),
    CONSTRAINT FK_DIRECCIONTOCOLONIA FOREIGN KEY(IdColonia) REFERENCES COLONIA(IdColonia)
);

CREATE TABLE SUCURSAL(
    IdSucursal INT AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    IdDireccion INT NOT NULL,
    Telefono VARCHAR(12),
    FechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SUCURSAL PRIMARY KEY(IdSucursal),
    CONSTRAINT FK_SUCURSALTODIRECCION FOREIGN KEY(IdDireccion) REFERENCES DIRECCION(IdDireccion)
);

SELECT * FROM CODIGOPOSTAL;

DROP FUNCTION  IF EXISTS ObtenerDireccionBYCP;

CREATE FUNCTION ObtenerDireccionBYCP(ID varchar(10))
RETURNS VARCHAR(100)
    DETERMINISTIC
    BEGIN
        DECLARE DIRECCION VARCHAR(100);
        SET DIRECCION = (SELECT CONCAT(E.Estado, ' ', M.Municipio, ' ', C2.Colonia, ' ', C.CodigoPostal) AS DIRECCION FROM ESTADO AS E INNER JOIN MUNICIPIO AS M ON E.IdEstado = M.IdEstado INNER JOIN CODIGOPOSTAL AS C ON M.IdMunicipio = C.IdMunicipio INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = ID LIMIT 1);
        RETURN DIRECCION;
    end;

DROP FUNCTION IF EXISTS FN_ObtenerDistancia;
CREATE FUNCTION FN_ObtenerDistancia(CODIGO1 varchar(10), CODIGO2 VARCHAR(10))
RETURNS DOUBLE
    DETERMINISTIC
    BEGIN
        DECLARE DISTANCIA DOUBLE;
        DECLARE LAT1 DOUBLE;
        DECLARE LAT2 DOUBLE;
        DECLARE LON1 DOUBLE;
        DECLARE LON2 DOUBLE;

        SET LAT1 = (SELECT C.Latitud FROM CODIGOPOSTAL AS C WHERE C.CodigoPostal = CODIGO1);
        SET LAT2 = (SELECT C.Latitud FROM CODIGOPOSTAL AS C WHERE C.CodigoPostal = CODIGO2);

        SET LON1 = (SELECT C.Longitud FROM CODIGOPOSTAL AS C WHERE C.CodigoPostal = CODIGO1);
        SET LON2 = (SELECT C.Longitud FROM CODIGOPOSTAL AS C WHERE C.CodigoPostal = CODIGO2);

        SET DISTANCIA = 6371 * 2 * ASIN(
        SQRT(
            POWER(SIN(RADIANS(LAT2 - LAT1) / 2), 2) +
            COS(RADIANS(LAT1)) * COS(RADIANS(LAT2)) *
            POWER(SIN(RADIANS(LON2 - LON1) / 2), 2)
        )
    );
        RETURN DISTANCIA;
    end;


SELECT FN_ObtenerDistancia('38800', '37000');

SELECT ObtenerDireccionBYCP('01010');

select * FROM CODIGOPOSTAL where CodigoPostal = '68025';
SELECT IdEstado FROM MUNICIPIO WHERE IdMunicipio = 266;

SELECT * FROM COLONIA WHERE IdCodigoPostal is null;

SELECT * FROM MUNICIPIO WHERE Municipio = 'Tuxpan';

SELECT * FROM MUNICIPIO;

SELECT * FROM CODIGOPOSTAL WHERE CodigoPostal = '20263';

SELECT CONCAT(E.Estado, ' ', M.Municipio, ' ', C2.Colonia, ' ', C.CodigoPostal) AS DIRECCION FROM ESTADO AS E INNER JOIN MUNICIPIO AS M ON E.IdEstado = M.IdEstado INNER JOIN CODIGOPOSTAL AS C ON M.IdMunicipio = C.IdMunicipio INNER JOIN COLONIA C2 on C.IdCodigoPostal = C2.IdCodigoPostal WHERE C.CodigoPostal = '010101'


CREATE TABLE ESTADOCSV(
    IdEstado INT,
    Estado VARCHAR(50)
);

CREATE TABLE MUNICIPIOCSV(
    IdMunicipio INT,
    Municipio VARCHAR(50),
    IdEstado INT
);

CREATE TABLE CODIGOPOSTALCSV(
    IdCodigoPostal INT,
    CodigoPostal VARCHAR(10),
    IdMunicipio INT,
    Latitud DECIMAL(10,6),
    Longitud DECIMAL(10,6)
);

CREATE TABLE COLONIACSV(
    IdColonia INT,
    Colonia VARCHAR(75),
    IdCodigoPostal INT
);